baseURL = "https://www.danblundell.com/"
languageCode = "en-us"
title = "Dan Blundell"
theme = "hyde"
googleAnalytics = "UA-43692868-1"
pygmentsStyle = "dracula"
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog/"
    weight = 1000
  #[[menu.main]]
  #  identifier = "weeknotes"
  #  name = "Weeknotes"
  #  title = "Weeknotes"
  #  url = "/weeknotes/"
  #  weight = -110
  

[permalinks]
  blog = "/:year/:month/:title/"
  weeknotes = "weeknotes/:year/week-:slug/"
[params]
  themeColor = "theme-base-dan"
  description = " "

