baseURL = "https://www.danblundell.com/"
languageCode = "en-us"
title = "Dan Blundell"
theme = "hyde"
googleAnalytics = "UA-43692868-1"

#[menu]
#  [[menu.main]]
#    identifier = "blog"
#    name = "Blog"
#    title = "Blog"
#    url = "/blog/"
#    weight = -110

[permalinks]
  blog = "/:year/:month/:title/"
[params]
  themeColor = "theme-base-dan"
  description = " "
